module.exports = {
    "Osaka_Auction" : ["Shinjuku_Diner", "Customs"],
    "Banda_Aceh_Night" : ["Robot_Restaurant", "Osaka_Arrival"],
    "Catching_a_Fish" : ["Morning_Load_Out", "Osaka_Arrival"],
    "Fish_For_Sale" : ["Osaka_Sweeping", "Robot_Restaurant"],
    "Cutting_Apart" : ["Osaka_Buyer", "Ice_Machines"],
    "Now_We_Wait" : ["Fish_POV", "Cutting_Apart"],
    "Ice_Machines" : ["Nova", "Fish_For_Sale"],
    "Igarashi" : ["Cutting_Apart", "Nova"],
    "Robot_Restaurant" : ["Mr._Sushi", "Shinjuku_Diner"],
    "Shinjuku_Diner" : ["Igarashi", "Morning_Load_Out"],
    "Mr._Sushi" : ["Becak", "Out_to_Sea"],
    "Osaka_Buyer" : ["Banda_Aceh_Night", "Fish_POV"],
    "Out_to_Sea" : ["Becak_Fish_For_Sale"],
    "Becak" : ["Osaka_Buyer", "Catching_a_Fish"],
    "Morning_Load_Out" : ["Fish_For_Sale", "Cutting_Apart"],
    "Customs" : ["Catching_a_Fish", "Boxing"],
    "Nova" : ["Osaka_Auction", "Mr._Sushi"],
    "Truck_to_Airport" : ["Osaka_Auction", "Banda_Aceh_Night"],
    "Osaka_Sweeping" : ["Now_We_Wait", "Truck_to_Airport"],
    "Boxing" : ["Now_We_Wait", "Osaka_Auction"],
    "Fish_POV" : ["Out_to_Sea", "Truck_to_Airport"],
    "Osaka_Arrival" : ["Osaka_Sweeping", "Ice_Machines"]
}